ansible_connection: ssh
ansible_ssh_port: 22
ansible_user: root
#Can get IP address with "docker-machine ip default"
ansible_ssh_host: 46.101.224.24

ansible_ssh_private_key_file: /Users/samanthony/.docker/machine/machines/address-book-demo/id_rsa



