#You will need to log into bitbucket/Github interface and install the deployment keys there
#https://confluence.atlassian.com/bitbucket/use-deployment-keys-294486051.html

- name: setup git provider deployment private key
  copy:
    src: "{{ git_deployment_key_src_path }}"
    dest: "{{ git_deployment_key_dest_path }}"
    mode: 0600
  when: repo_enabled

- name: delete intended repo folder if it exists (application)
  file: path={{ repo_application_path }} state=absent
  when: repo_enabled


